apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktlabo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktlabo
  template:
    metadata:
      labels:
        app: oktlabo
    spec:
      containers:
      - image: okteto.dev/oktlabo:latest
        name: oktlabo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d0fe0c8e-c1a8-4c55-9715-56c913318249"
        - name: Vless_Path
          value: "/vl12c1"
        - name: Vmess_UUID
          value: "d0fe0c8e-c1a8-4c55-9715-56c913318249"
        - name: Vmess_Path
          value: "/vm12c1"
        - name: Share_Path
          value: "/v2link"
